// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZQRG9URSPrdntz84Jjyu4bBiT5pvAR0Y',
    appId: '1:20599031368:web:330943cc42c6c77a67ba7d',
    messagingSenderId: '20599031368',
    projectId: 'test-38eda',
    authDomain: 'test-38eda.firebaseapp.com',
    storageBucket: 'test-38eda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8Htm43kssnU5jtprwfS5q_3I20pub8s',
    appId: '1:20599031368:android:4d7e7d1131e2d02367ba7d',
    messagingSenderId: '20599031368',
    projectId: 'test-38eda',
    storageBucket: 'test-38eda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmzFr90E04nIujAc9cNitzJlAZlaKsFdE',
    appId: '1:20599031368:ios:ab89f3460644f5dc67ba7d',
    messagingSenderId: '20599031368',
    projectId: 'test-38eda',
    storageBucket: 'test-38eda.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmzFr90E04nIujAc9cNitzJlAZlaKsFdE',
    appId: '1:20599031368:ios:ab89f3460644f5dc67ba7d',
    messagingSenderId: '20599031368',
    projectId: 'test-38eda',
    storageBucket: 'test-38eda.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZQRG9URSPrdntz84Jjyu4bBiT5pvAR0Y',
    appId: '1:20599031368:web:01cbbfc64e46edca67ba7d',
    messagingSenderId: '20599031368',
    projectId: 'test-38eda',
    authDomain: 'test-38eda.firebaseapp.com',
    storageBucket: 'test-38eda.appspot.com',
  );
}